name: 'CI: Python'
description: 'Run Python CI checks'

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.8.x'

runs:
  using: 'composite'

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # fetch the full history for Nx to determine affected projects
        fetch-depth: 0
    - name: Set Nx base commit
      uses: nrwl/nx-set-shas@v3
      with:
        main-branch-name: 'main'
    - name: Setup environment
      uses: secretflow/web-ci/.github/actions/ci-setup@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run checks
      shell: bash
      run: |
        pnpm exec nx affected \
          -t lint:black \
          -t lint:ruff \
          -t test:pytest \
          -t typecheck:pyright
