name: 'CI: Setup'
description: 'Setup CI environment'

inputs:
  node-version:
    description: 'Node version'
    required: true
  python-version:
    description: 'Python version'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org/'
        cache: 'pnpm'

    - name: Setup Python ${{ inputs.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Setup Nx cache
      uses: actions/cache@v3
      with:
        path: node_modules/.cache/nx
        # Including SHA in the key causes a cache miss with every commit
        # This is desired because we want cache results to always be updated
        # while we will be using restore-keys to select the closest cache
        key: cache-nx-${{ github.ref }}-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.node-version }}-${{ github.sha }}
        restore-keys: |
          cache-nx-${{ github.ref }}-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.node-version }}
          cache-nx-${{ github.ref }}-${{ runner.os }}-${{ inputs.python-version }}
          cache-nx-${{ github.ref }}-${{ runner.os }}
          cache-nx-${{ github.ref }}
          cache-nx

    - name: Install Node dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Install Python dependencies
      shell: bash
      run: pip install -r requirements-dev.lock

    - name: Setup packages
      shell: bash
      run: pnpm run ci:setup
