# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  devcontainer-publish:
    docker:
      - image: cimg/base:stable
    resource_class: xlarge

    parameters:
      platform:
        type: string
        default: linux/amd64
      tag:
        type: string
        default: latest
      python_version:
        type: integer
        default: 3.8

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and publish
          command: |
            export IMAGE_NAME=secretflow/devcontainer-web:<< parameters.tag >>

            docker buildx build \
              --platform=<< parameters.platform >> \
              --build-arg NODE_VERSION=18 \
              --build-arg PYTHON_VERSION=<< parameters.python_version >> \
              -f devcontainer.Dockerfile \
              -t ${IMAGE_NAME} \
              --progress=plain \
              .

            docker login -u secretflow -p ${DOCKER_DEPLOY_TOKEN}
            docker push ${IMAGE_NAME}

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  devcontainer-publish-amd64:
    jobs:
      - devcontainer-publish:
          filters:
            branches:
              only:
                - main
          platform: linux/amd64
          tag: latest

  devcontainer-publish-arm64:
    jobs:
      - devcontainer-publish:
          filters:
            branches:
              only:
                - main
          python_version: 3.10
          platform: linux/arm64
          tag: unstable-arm64
