# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  devcontainer-publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and publish
          command: |
            docker buildx create \
              --name builder \
              --platform linux/amd64,linux/arm64 \
              --use

            docker buildx build \
              --build-arg NODE_VERSION=18 \
              --build-arg PYTHON_VERSION=3.8 \
              -f devcontainer.Dockerfile \
              -t secretflow/devcontainer-web:latest \
              --platform linux/amd64,linux/arm64 \
              --progress=plain \
              .

            docker login -u secretflow -p ${DOCKER_DEPLOY_TOKEN}
            docker push secretflow/devcontainer-web:latest

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  devcontainer-publish:
    jobs:
      - devcontainer-publish
