name: 'CI: JavaScript'

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: 'Node version'
        required: false
        default: '16.20.x'

permissions:
  contents: read
  actions: read # required by nrwl/nx-set-shas

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: secretflow/web-ci/.github/actions/ci-setup@main
        with:
          node-version: ${{ inputs.node-version }}

      - name: Run checks
        shell: bash
        run: |
          pnpm run ci:javascript
