name: 'CI: Python'

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: 'Python version'
        required: false
        default: '3.8.x'

permissions:
  contents: read
  actions: read # required by nrwl/nx-set-shas

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch the full history for Nx to determine affected projects
          fetch-depth: 0
      - name: Set Nx base commit
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'
      - name: Setup environment
        uses: secretflow/web-ci/.github/actions/ci-setup@main
        with:
          python-version: ${{ inputs.python-version }}
      - name: Run checks
        shell: bash
        run: |
          pnpm exec nx affected \
            -t lint:black \
            -t lint:ruff \
            -t test:pytest \
            -t typecheck:pyright
