name: 'Release: Publish'

on:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write # to create tags

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: secretflow/web-ci/.github/actions/ci-setup@main

      - name: Authenticate with NPM
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Publish
        run: pnpm run ci:release
        env:
          HATCH_INDEX_USER: __token__ # For PyPI
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}

      - name: Create and push tags
        # Use github-actions as user.name and user.email
        run: |
          git config user.name $(git --no-pager show -s --format='%an')
          git config user.email $(git --no-pager show -s --format='%ae')
          pnpm exec changeset tag
          git push origin --follow-tags

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            packages/*/dist/**
            pyprojects/*/dist/**
