name: 'Release: Publish'

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: 'Node version'
        required: true
      python-version:
        type: string
        description: 'Python version'
        required: true
    secrets:
      NPM_TOKEN:
        required: true
      PYPI_TOKEN:
        required: true
      BOT_APP_ID:
        required: true
      BOT_PRIVATE_KEY:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: secretflow/web-ci/.github/actions/ci-setup@main
        with:
          node-version: ${{ inputs.node-version }}
          python-version: ${{ inputs.python-version }}

      - name: Build
        run: pnpm run ci:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            packages/*/dist/**
            pyprojects/*/dist/**

      - name: Authenticate with NPM
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Publish
        run: pnpm run ci:publish
        env:
          HATCH_INDEX_USER: __token__ # For PyPI
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}

      # Generate GitHub token for changesets/action using secretflow-bot
      # This allows other actions to assume the bot's identity
      # when performing Git operations
      - name: Generate GitHub token
        id: generate-token
        uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Create and push tags
        # Use github-actions as user.name and user.email
        run: |
          git config user.name "${{steps.generate-token.outputs.bot_name}}[bot]"
          git config user.email "${{steps.generate-token.outputs.bot_name}}[bot]@users.noreply.github.com"
          pnpm exec changeset tag
          git push origin --follow-tags
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.bot_token }}
