name: 'Release: Publish'

on:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write # to create tags

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: secretflow/web-ci/.github/actions/ci-setup@main

      - name: Authenticate with NPM
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Publish
        run: pnpm run ci:release
        env:
          HATCH_INDEX_USER: __token__ # For PyPI
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}

      - name: Tag
        run: pnpm exec changeset tag && git push --tags
